  version: 3
  tasks:
    dev:
      cmds:
        - air
    build:
      cmds:
        - task build:all-assets
        - go build -o ./bin/chia-goths
    build:all-assets:
      cmds:
        - ls -l internal/apps | grep '^d' | awk '{print $9}' | parallel --colsep ' ' APP={1} npm run build
    deploy:flyio:
      cmds:
        - flyctl deploy
