  version: 3
  tasks:
    dev:
      deps:
        - air
    build:
      cmds:
        - task:build:all-assets
        - go build -o ./bin/chia-goths
    build:all-assets:
      cmds:
        - |
          for script in $(jq -r '.scripts | to_entries | map(select(.key | startswith("build:"))) | .[].key' package.json); do
            echo "Running $script..."
            npm run $script
          done
    deploy:flyio:
      cmds:
        - flyctl deploy